# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SALIDO Wine Club (iOS Challenge)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SALIDO Wine Club (iOS Challenge)
  pod 'Realm', '~> 2.7'
  pod 'AFNetworking'
  pod 'Mantle'
  pod 'iOS-Slide-Menu'
end
